### ISSUE TITLE
Leo Bodnar eight axis joystick

### ISSUE THREAD

**Issue by davieli2** [Zuzu-Typ/XInput-Python#3]
Hi,
I connected a LeoBodnar BU0836A with eight axis joystick, windows driver see everything but XInput is not able to catch the joystick .. any idea ?!

**Comment by Zuzu-Typ** [comment]
Hi davieli2,

Windows controllers are usually one of two types:
DirectInput compatible or XInput compatible.

Where any XInput compatible controller also works with DirectInput.

DirectInput is the predecessor of XInput and does not support multiple triggers, rumble or battery information, that said, XInput is very much tailored to the XBox controllers, which is why it only supports the peripherals that a normal XBox controller would have too.

Your controller is probably not XInput compatible, thus it's not recognized.
